const IS_LOGGED_IN = 'IS_LOGGED_IN';
const USER_TOKEN = 'USER_TOKEN';
const IS_COMPLETE_ON_BOARDING = 'IS_COMPLETE_ON_BOARDING';
const IS_STORE_GCM_TOKEN = 'IS_STORE_GCM_TOKEN';
const LOGIN_CREDENTIALS = 'LOGIN_CREDENTIALS';

export {
  IS_LOGGED_IN,
  USER_TOKEN,
  IS_COMPLETE_ON_BOARDING,
  IS_STORE_GCM_TOKEN,
  LOGIN_CREDENTIALS,
};
