import {StyleSheet} from 'react-native';
import {fonts} from './fonts.style.asset';
import rs from './responsiveSize.style.asset';
import {colors} from './colors.style.asset';

export const typographies = StyleSheet.create({
  interSemiBold16: {
    fontFamily: fonts.inter600,
    fontSize: rs(16),
    lineHeight: rs(26),
    color: colors.white,
    textAlign: 'left',
  },
  interSemiBold28: {
    fontFamily: fonts.inter600,
    fontSize: rs(28),
    lineHeight: rs(33),
    color: colors.black,
    textAlign: 'left',
  },
  interSemiBold12: {
    fontFamily: fonts.inter600,
    fontSize: rs(12),
    lineHeight: rs(18),
    color: colors.grey,
    textAlign: 'left',
  },
  interSemiBold20: {
    fontFamily: fonts.inter600,
    fontSize: rs(20),
    lineHeight: rs(24),
    color: colors.black,
    textAlign: 'left',
  },
  interSemiBold24: {
    fontFamily: fonts.inter600,
    fontSize: rs(24),
    lineHeight: rs(32),
    color: colors.black,
    textAlign: 'left',
  },
  interSemiBold34: {
    fontFamily: fonts.inter600,
    fontSize: rs(34),
    color: colors.white,
    textAlign: 'left',
  },
  interSemiBold14: {
    fontFamily: fonts.inter600,
    fontSize: rs(14),
    lineHeight: rs(21),
    color: colors.orange,
    textAlign: 'left',
  },
  interSemiBold10: {
    fontFamily: fonts.inter600,
    fontSize: rs(10),
    lineHeight: rs(19),
    color: colors.black,
    textAlign: 'left',
  },
  interNormal10: {
    fontFamily: fonts.inter400,
    fontSize: rs(10),
    lineHeight: rs(19),
    color: colors.black,
    textAlign: 'left',
  },
  interNormal16: {
    fontFamily: fonts.inter400,
    fontSize: rs(16),
    lineHeight: rs(21),
    color: colors.black,
    textAlign: 'left',
  },
  interNormal12: {
    fontFamily: fonts.inter400,
    fontSize: rs(12),
    lineHeight: rs(18),
    color: colors.grey,
    textAlign: 'left',
  },
  interNormal14: {
    fontFamily: fonts.inter400,
    fontSize: rs(14),
    lineHeight: rs(20),
    color: colors.grey,
    textAlign: 'left',
  },
  bodyText1: {
    fontFamily: fonts.inter400,
    fontSize: rs(14),
    color: colors.grey,
    textAlign: 'left',
  },
  interMedium16: {
    fontFamily: fonts.inter500,
    fontSize: rs(16),
    lineHeight: rs(21),
    color: colors.grey,
    textAlign: 'left',
  },
  interMedium20: {
    fontFamily: fonts.inter500,
    fontSize: rs(20),
    lineHeight: rs(24),
    color: colors.grey,
    textAlign: 'left',
  },
  interMedium14: {
    fontFamily: fonts.inter500,
    fontSize: rs(14),
    lineHeight: rs(16),
    color: colors.grey,
    textAlign: 'left',
  },
  interMedium12: {
    fontFamily: fonts.inter500,
    fontSize: rs(12),
    lineHeight: rs(16),
    color: colors.grey,
    textAlign: 'left',
  },
  interMedium11: {
    fontFamily: fonts.inter500,
    fontSize: rs(11),
    lineHeight: rs(16),
    color: colors.grey,
    textAlign: 'left',
  },
  searchInput: {
    fontFamily: fonts.inter500,
    fontSize: rs(14),
    color: colors.grey,
    textAlign: 'left',
  },
  interBold16: {
    fontFamily: fonts.inter700,
    fontSize: rs(16),
    lineHeight: rs(20),
    color: colors.white,
    textAlign: 'left',
  },
  interBold12: {
    fontFamily: fonts.inter700,
    fontSize: rs(12),
    lineHeight: rs(17),
    color: colors.white,
    textAlign: 'left',
  },
});
